### ISSUE TITLE
Set up top navigation with tabs

### ISSUE THREAD

**Issue by nathanbaleeta** [nathanbaleeta/ureport-mobile#1]
Build bottom navigation for app with links to `polls` and `stories` pages:

- [x] Create a new branch from `develop` called `top-navigation`. **Hint:** git checkout -b `new-branch` `existing-branch`
- [x] Create a `TabController`.
- [x] Create the tabs for `polls` and `stories`
- [x] Create content for each tab including appropriate [icons](https://api.flutter.dev/flutter/material/Icons-class.html)
- [x] Commit the changes (as a single commit). 
- [x] Push changes to github. **Hint:**  `git push --set-upstream origin top-navigation`
- [x] Open a pull-request.

**Hint:**
https://flutter.dev/docs/cookbook/design/tabs

**Comment by alee8599** [comment]
Just for curiosity sake, I was wondering why we were doing bottom navigation because our mockup has top bar navigation.
